import Footer from "./footer";
import "./globals.css";
import Header from "./header";

export const metadata = {
  title: "United Hands",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header name={'United Hands'} />
        {children}
        <br />
        <Footer />
      </body>
    </html>
  );
}
