
export const userData = [
  { id: 1, name: 'superadmin', phoneNumber: '11111111', password: '11111111', role: 'SUPERADMIN' },
  { id: 2, name: 'admin', phoneNumber: '2222222222', password: '2222222222', role: 'ADMIN' },
  { id: 3, name: 'user', phoneNumber: '3333333333', password: '3333333333', role: 'USER' },
  { id: 4, name: 'Ramachandra', phoneNumber: '7093419328', password: '7093419328', role: 'SUPERADMIN' },
  { id: 5, name: 'Sasi', phoneNumber: '8522966265', password: '8522966265', role: 'ADMIN' },
  { id: 6, name: 'Sarath', phoneNumber: '9676091908', password: '9676091908', role: 'USER' },
  { id: 7, name: 'Venkata Reddy', phoneNumber: '', password: '', role: 'USER' },
  { id: 8, name: 'Nani', phoneNumber: '', password: '', role: 'USER' },
  { id: 9, name: 'Govardhan', phoneNumber: '', password: '', role: 'USER' },
  { id: 10, name: 'Ganesh', phoneNumber: '', password: '', role: 'USER' },
  { id: 11, name: 'venkatesh', phoneNumber: '', password: '', role: 'USER' },
  { id: 12, name: 'Narendra', phoneNumber: '', password: '', role: 'USER' },
  { id: 13, name: 'vinod', phoneNumber: '', password: '', role: 'USER' },
  { id: 14, name: 'Kiran', phoneNumber: '', password: '', role: 'USER' },
  { id: 15, name: 'Sathish', phoneNumber: '', password: '', role: 'USER' },
  { id: 16, name: 'Sai Taja', phoneNumber: '', password: '', role: 'USER' },
  { id: 17, name: 'Krishna', phoneNumber: '', password: '', role: 'USER' },
  { id: 18, name: 'Vigin', phoneNumber: '', password: '', role: 'USER' },
  { id: 19, name: 'Dinesh', phoneNumber: '', password: '', role: 'USER' },
  { id: 20, name: 'Harish', phoneNumber: '', password: '', role: 'USER' },
  { id: 21, name: 'Sudhakar', phoneNumber: '', password: '', role: 'USER' },
  { id: 22, name: 'Love Reddy', phoneNumber: '', password: '', role: 'USER' },
  { id: 23, name: 'Mohan Babu', phoneNumber: '', password: '', role: 'USER' },
  { id: 24, name: 'Suresh', phoneNumber: '', password: '', role: 'USER' },
  { id: 25, name: 'Raju', phoneNumber: '', password: '', role: 'USER' },
  { id: 26, name: 'Balaji', phoneNumber: '', password: '', role: 'USER' },
  { id: 27, name: 'Rakesh', phoneNumber: '', password: '', role: 'USER' },
  { id: 28, name: 'Giri', phoneNumber: '', password: '', role: 'USER' },
  { id: 29, name: 'Rakesh', phoneNumber: '', password: '', role: 'USER' },
  { id: 30, name: 'Muniraj', phoneNumber: '', password: '', role: 'USER' },
  { id: 32, name: 'Trust Group', phoneNumber: '', password: '', role: 'USER' }
];
